{% set version = "0.0.3" %}

package:
  name: libimage
  version: {{ version }}

source:
  - git_url: https://github.com/carterbox/libimage.git
    git_tag: master

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools_scm_git_archive
  run:
    - numpy
    - python >=3.6

test:
  imports:
    - libimage
  commands:
    - python -c "import libimage; libimage.load('coins')"

about:
  home: https://github.com/carterbox/libimage
  license: Creative Commons Attribution-ShareAlike 4.0
  license_family: CC
  license_file: LICENSE
  summary: 'Provides large (2k) test images as NumPy arrays.'
  dev_url: https://github.com/carterbox/libimage
